config/routes.rb
Rails.application.routes.draw do
  get 'media/index'
  
  resources :trends
  
  root 'media#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :text, presence: true, length:{ in: 1..140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  def index
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
end

app/controllers/trends_controller.rb
class TrendsController < ApplicationController
  def index
    @trends = Post.all
  end
  
    def show
    @tweet = Post.find(params[:id])
    end
    
    def new
      @tweet = Post.new
    end
    
    def edit
      @tweet = Post.find(params[:id])
    end
    
    def create
        @tweet = Post.new(tweet_params)
      if @tweet.save
        redirect_to new_trend_url
      else
         render 'new'
      end
    end
    
    def update
        @tweet = Post.find(params[:id])
 
      if @tweet.update(tweet_params)
         redirect_to new_trend_url
      else
         render 'edit'
      end
    end
    
    def destroy
      @tweet = Post.find(params[:id])
      @tweet.destroy
 
      redirect_to trends_path
    end
    
    private
      def tweet_params
        params.require(:post).permit(:title, :text)
      end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/trends_helper.rb
module TrendsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApp</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
    <ul >
      <li ><%= link_to 'Home', controller: 'media' %></li>
      <li ><%= link_to 'Open Trends', controller: 'trends' %></li>
      <li ><%= link_to 'Create Tweet', new_trend_url %></li>
    </ul>
  </header>
  
    <%= yield %>
    
    <footer>
    <p>TwitterClone Application</p>
    <p>© 2018 Copyright MAGEZA Adolphe.</p>
  </footer>

  </body>
</html>

app/views/media/index.html.erb
<div class="container">
   <h1><center><p>Hello!</p>Welcome to my TwitterClone Rails Application!</center></h1>
</div>

app/views/trends/_form.html.erb
<%= form_with model: @tweet, url: trends_path, local: true do |form| %>
 
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@tweet.errors.count, "error") %> prohibited
        this Trend from being Twitted:
      </h2>
      <ul>
        <% @tweet.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/trends/edit.html.erb
<h1>Edit Trend</h1>

<%= render 'form' %>

<button type="button" class="btn btn-outline-primary btn-sm"><%= link_to 'Back', trends_url %></button>

app/views/trends/index.html.erb
<h1>Media Trends List</h1>
<table>
  <tr>
    <th>Name</th>
    <th>Message</th>
    <th colspan="2"></th>
  </tr>
 
  <% @trends.each do |tweet| %>
    <tr>
      <td><%= tweet.title %></td>
      <td><%= tweet.text %></td>
      <td><button type="button" class="btn btn-outline-primary btn-sm"><%= link_to 'Show', trend_url(tweet) %></button></td>
      <td><button type="button" class="btn btn-outline-primary btn-sm"><%= link_to 'Edit', edit_trend_url(tweet) %></button></td>
      <td><button type="button" class="btn btn-outline-primary btn-sm"><%= link_to 'Destroy', trend_url(tweet),
              method: :delete,
              data: { confirm: 'Are you sure? Do you like to delete this Post?' } %></button></td>
    </tr>
  <% end %>
</table>

app/views/trends/new.html.erb
<h1>Create New Tweet</h1>

<%= render 'form' %>

<button type="button" class="btn btn-outline-primary btn-sm"><%= link_to 'Back', trends_url %></button>

app/views/trends/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @tweet.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @tweet.text %>
</p>
<button type="button" class="btn btn-outline-primary btn-sm"><%= link_to 'Edit', edit_trend_url %></button>
<button type="button" class="btn btn-outline-primary btn-sm"><%= link_to 'Back', trends_url %></button>